name: Python Concourse Docker Image Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix_json: ${{ steps.output_data.outputs.matrix_json }}
    steps:

      - name: Check out
        uses: actions/checkout@v2
        
      - name: Get Diff Action
        uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: |
            python/Dockerfile
          
      - name: Set output
        if: env.GIT_DIFF_FILTERED
        id: output_data
        shell: bash
        run: |
             matrixJsonObject=$(echo $GIT_DIFF_FILTERED | jq --raw-input --raw-output 'gsub("'"'"'"; "") | split(" ") | map( { Dockerfile:.} ) | { include:. } | tostring')  
             echo "::set-output name=matrix_json::$matrixJsonObject"
     
  docker_image_build:
    needs: build_matrix
    if: needs.build_matrix.outputs.matrix_json
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.build_matrix.outputs.matrix_json) }}
    steps: 
      - name: Check out
        uses: actions/checkout@v2


      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2.3.0
        with:
          images: teliaoss/concourse-python,ghcr.io/telia-oss/concourse-python
          flavor: |
            latest=true
          tags: |
            type=sha,enable=true,priority=500,prefix=sha-
            type=edge,enable=false,priority=700,branch=$repo.default_branch
            type=semver,enable=false,priority=900,pattern={{raw}},value=v${{ env.versionTag }}    
          labels: |
            maintainer=Telia OSS
            org.opencontainers.image.title=concourse-python
            org.opencontainers.image.description=Alpine python toolbox for use in Concourse pipelines. 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.TELIAOSS_GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }} 
          file: ./${{ matrix.Dockerfile }} 
          
  docker_image_build_daily:
    needs: build_matrix
    if: "!needs.build_matrix.outputs.matrix_json"
    runs-on: ubuntu-latest
    steps: 
      - name: Check out
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2.3.0
        with:
          images: teliaoss/concourse-python,ghcr.io/telia-oss/concourse-python
          flavor: |
            latest=true
          tags: |
            type=sha,enable=true,priority=500,prefix=sha-
            type=edge,enable=false,priority=700,branch=$repo.default_branch
            type=schedule,enable=true,priority=1000,pattern={{date 'YYYYMMDD'}}    
          labels: |
            maintainer=Telia OSS
            org.opencontainers.image.title=concourse-python
            org.opencontainers.image.description=Alpine python toolbox for use in Concourse pipelines. 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.TELIAOSS_GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}  
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }} 
          file: ./python/Dockerfile        