name: Build and Publish Docker Images

on:
  push:
    branches: [ orange-master ]
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
    branches: [ orange-master ]
  workflow_dispatch:

env:
  DOCKER_FILE_PATH: "fly"
jobs:
  build_and_publish:
    name: build and publish
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    -
      name: publish image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ${{env.DOCKER_FILE_PATH}}
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{github.sha}}
    -
      name: publish tagged image
      if: github.ref_type == 'tag'
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        context: ${{env.DOCKER_FILE_PATH}}
        tags: |
          ghcr.io/${{ github.repository }}:${{github.ref_name}}
